twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        Market: '@App\Service\MarketService'

    form_themes:
        ['bootstrap_4_layout.html.twig']

when@test:
    twig:
        strict_variables: true
